#include<stdio.h>
#include<conio.h>
main()
{
clrscr();
printf("\n--------");
printf("\nl\t|");
printf("\nR\t|");
printf("\nN\t|");
printf("\nW\t|");
printf("\nl\t|");
printf("\n--------");
getch();
}